### ISSUE TITLE
Wishlist retrieving is broken

### ISSUE THREAD

**Issue by fadzlan** [BlueRaja/SteamWishlistSharedLibrary#1]
It seems that few things has since changed.

1. The wishlist URL has changed from `https://steamcommunity.com/wishlist/id/<uservanityid>/` to `https://store.steampowered.com/wishlist/id/<uservanityid>/`
2. For some reason, even when the URL has been corrected, and the selector updated, the DOM parser is still unable to get wishlist.
3. Wishlist from DOM only have 16 items at a time.
4. Right now, we can get the wishlist data from `https://store.steampowered.com/wishlist/id/<uservanityid>/wishlistdata/`, which retrieves all of the wishlist in JSON format.

The current XML retrieving and parsing of existing game still works.

If I manage to get around it, I may submit a pull request. No promises yet.

**Comment by BlueRaja** [comment]
Neat, didn't know anyone actually used this. I updated it to work with the latest version of Steam.

**Comment by fadzlan** [comment]
Nice. Thanks for the updates.
