### ISSUE TITLE
Program doesn't work for some reason

### ISSUE THREAD

**Issue by ginatonik** [BlueRaja/SteamWishlistSharedLibrary#2]
I'm not sure if this program needs to be updated. It doesn't work for me. It's pretty self-explanatory so I don't think I'm doing anything wrong. Probably what the issue is, is that my friend's profile is set to private. If that's the case, it should possibly be mentioned in the instructions. I'm not sure if there's a way around that, sadly.

![image](https://github.com/BlueRaja/SteamWishlistSharedLibrary/assets/71720850/3c3a4d1f-4745-40d7-94af-9fad20f9dc35)

**Comment by BlueRaja** [comment]
Yes, both profiles are required to have their games lists publicly listed.
